#!/usr/bin/env python3
"""Build the Cris Santos Company scenario library from the three source layers.

Layers (edit these, never the generated output):
  00_universal/   frameworks, crosswalks, sources, 10 project methods and templates
  01_tiers/       six size tiers and the tier-by-project scaling matrix
  02_verticals/   NAICS sectors (parents) and CISA sectors (children): profile, requirements, notifications

Generated by this script:
  02_verticals/**/overlay.md          readable summary of each vertical (always rewritten)
  03_scenarios/**/README.md           meeting brief per tier x vertical (always rewritten)
  03_scenarios/**/P*/_context.md      what the project means in that scenario (always rewritten)
  03_scenarios/**/P*/<templates>      working files, created only if missing (your work is never overwritten)
  03_scenarios/INDEX.md               navigation matrix

Usage: python3 tools/build_scenarios.py [--force-templates]
"""
import csv, datetime, pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
U, T, V, S = (ROOT / d for d in ("00_universal", "01_tiers", "02_verticals", "03_scenarios"))
COMPANY = "Cris Santos Company"
FORCE = "--force-templates" in sys.argv
TODAY = datetime.date.today().isoformat()
GENERATED = "<!-- GENERATED by tools/build_scenarios.py. Edit the source layers, then rebuild. -->"


def rows(path):
    with open(path, newline="") as f:
        return list(csv.DictReader(f))


def profile(path):
    return {r["field"]: r["value"] for r in rows(path)} if path.exists() else {}


def md_escape(s):
    return (s or "").replace("|", "/").replace("\n", " ").strip()


def as_role(business):
    """'Acute-care hospital' -> 'an acute-care hospital'; keeps acronyms like 'B2B SaaS' intact."""
    b = business if business[:2].isupper() else business[0].lower() + business[1:]
    return ("an " if b[0].lower() in "aeiou" else "a ") + b


def money(musd):
    if musd >= 1000:
        return f"${musd / 1000:,.1f} billion"
    return f"${musd:,.1f} million" if musd >= 1 else f"${musd * 1e6:,.0f}"


# Cross-sector notification rows are skipped when the vertical already carries a sector-specific version.
DEDUP_KEYS = [r"52\.204-2[35]", r"6 U\.S\.C\. 681", r"Item 1\.05", r"breach notification statute"]


# ---------------------------------------------------------------- load layers
tiers = {t["tier_id"]: t for t in rows(T / "tiers.csv")}
scaling = {(r["tier_id"], r["project_id"]): r for r in rows(T / "tier-project-scaling.csv")}
projects = rows(U / "projects" / "projects.csv")
units = rows(V / "verticals.csv")
unit_by_id = {u["unit_id"]: u for u in units}
overrides = {(o["unit_id"], o["tier_id"]): o for o in rows(V / "scenario-industry-overrides.csv")}
sba = {s["naics6"]: s for s in rows(V / "sba-size-standards.csv")}
sector_names = {u["naics_sector"]: u["name"] for u in units if u["level"] == "naics_sector"}
cross_notify_path = U / "cross-sector" / "notification-baseline.csv"
cross_notify = rows(cross_notify_path) if cross_notify_path.exists() else []


def unit_dir(u, root):
    if u["level"] == "naics_sector":
        return root / u["slug"]
    return root / unit_by_id[u["parent_id"]]["slug"] / u["slug"]


# ---------------------------------------------------------------- sizing
def size_profile(tier_id, naics6):
    """Return representative size facts and SBA status for a tier and industry."""
    std = sba.get(naics6, {"basis": "none", "size_standard": "", "industry_title": ""})
    basis = std["basis"]
    cap = float(std["size_standard"]) if std["size_standard"] else None
    p = {"employees": None, "receipts": None, "assets": None, "flag": ""}
    if tier_id == "t1":
        p.update(employees=0, receipts=0.18)
    elif tier_id == "t2":
        p.update(employees=7, receipts=1.1)
        if basis == "assets_musd":
            p.update(assets=60.0)
    elif tier_id == "t3":
        if basis == "employees":
            p["employees"] = max(10, min(250, int(cap // 4)))
        elif basis == "assets_musd":
            p.update(employees=120, assets=round(cap * 0.6))
        else:
            small_cap = cap is not None and cap < 10
            p.update(employees=15 if small_cap else 60, receipts=round(cap * 0.6, 1) if cap else 12.0)
    elif tier_id == "t4":
        if basis == "employees":
            p["employees"] = 850
            if cap >= 900:
                p["flag"] = (f"The SBA standard for this industry is {int(cap):,} employees, so a company with fewer "
                             "than 1,000 employees still qualifies as small. This scenario is sized at 500-999 "
                             "employees (Census SUSB class) per the tier rule and remains SBA-small.")
        elif basis == "assets_musd":
            p.update(employees=600, assets=2500.0)
        else:
            p.update(employees=600, receipts=round(cap * 2, 1) if cap else 150.0)
    elif tier_id == "t5":
        p.update(employees=12000, receipts=4800.0)
    elif tier_id == "t6":
        p.update(employees=45000, receipts=18000.0)
    # SBA status
    if basis == "none":
        status = "Not applicable (no SBA size standard for this code)"
    else:
        value = {"employees": p["employees"], "receipts_musd": p["receipts"], "assets_musd": p["assets"]}[basis]
        unit = {"employees": "employees", "receipts_musd": "average annual receipts", "assets_musd": "total assets"}[basis]
        cap_txt = f"{int(cap):,} employees" if basis == "employees" else f"{money(cap)} in {unit}"
        small = value is not None and value <= cap
        status = f"{'Small' if small else 'Not small'} (SBA standard for NAICS {naics6}: {cap_txt}; 13 CFR 121.201)"
        if std.get("footnotes"):
            status += f". See footnote {std['footnotes']} in 13 CFR 121.201 for exceptions."
    p["sba_status"] = status
    p["industry_title"] = std.get("industry_title", "")
    return p


def headcount_text(p):
    e = p["employees"]
    return "Owner only (0 employees)" if e == 0 else f"{e:,} employees"


# ---------------------------------------------------------------- vertical overlays
def vertical_data(u):
    d = unit_dir(u, V)
    return {
        "dir": d,
        "profile": profile(d / "profile.csv"),
        "requirements": rows(d / "requirements.csv") if (d / "requirements.csv").exists() else [],
        "notifications": rows(d / "incident-notification.csv") if (d / "incident-notification.csv").exists() else [],
    }


def write_overlay(u, vd):
    pr, reqs, nots = vd["profile"], vd["requirements"], vd["notifications"]
    parent = unit_by_id.get(u["parent_id"])
    lines = [GENERATED, f"# Vertical overlay: {u['name']}", ""]
    if u["level"] == "naics_sector":
        lines.append(f"**Level:** NAICS 2022 sector {u['naics_sector']} (parent vertical)")
        kids = [k["name"] for k in units if k["parent_id"] == u["unit_id"]]
        if kids:
            lines.append(f"**CISA critical infrastructure sectors nested here:** {', '.join(kids)}")
    else:
        lines.append(f"**Level:** CISA critical infrastructure sector (child of NAICS {parent['naics_sector']} {parent['name']})")
    lines += [
        f"**Primary industry for {COMPANY}:** NAICS {u['primary_naics']} {sba.get(u['primary_naics'], {}).get('industry_title', '')}. {u['business']}.",
        f"**Primary system:** {u['primary_system']}",
        "",
        "## Regulators and sector risk management agency",
        pr.get("regulators", "[Pending research]"),
        "",
        "## Primary regulation for the gap analysis (P03)",
        f"**{pr.get('primary_regulation', '[Pending]')}**, {pr.get('primary_regulation_citation', '')}. {pr.get('primary_regulation_rationale', '')}",
        f"Source: {pr.get('primary_regulation_url', '')}",
        "",
        "## Key requirements (`requirements.csv`)",
        "| ID | Requirement | Citation | Applies to | Size thresholds / exemptions | Status |",
        "|---|---|---|---|---|---|",
    ]
    for r in reqs:
        lines.append(f"| {r['req_id']} | [{md_escape(r['short_name'])}]({r['source_url']}) | {md_escape(r['citation'])} | "
                     f"{md_escape(r['applies_to'])} | {md_escape(r['size_thresholds'])} | {md_escape(r['status'])} |")
    lines += ["", "## Incident and breach notification (`incident-notification.csv`)",
              "| Obligation | Citation | Deadline | Notify |", "|---|---|---|---|"]
    for n in nots:
        lines.append(f"| [{md_escape(n['obligation'])}]({n['source_url']}) | {md_escape(n['citation'])} | {md_escape(n['deadline'])} | {md_escape(n['notify'])} |")
    lines += ["", "## Sector context",
              f"- **Sensitive data:** {pr.get('sensitive_data', '')}",
              f"- **Critical systems:** {pr.get('critical_systems', '')}",
              f"- **Sector AI rules and guidance:** {pr.get('ai_specific', '') or 'None identified beyond cross-sector obligations'}",
              f"- **Assurance alternatives to SOC 2:** {pr.get('assurance_alternatives', '') or 'None noted'}",
              f"- **Scenario incident (P08):** {u['ir_scenario']}",
              f"- **Scenario AI use case (P10):** {u['ai_use_case']}"]
    if pr.get("notes"):
        lines += ["", "## Notes", pr["notes"]]
    lines += ["", f"_Last verified: {pr.get('last_verified', 'n/a')}. Unverified items are marked in the CSV `verified` column._", ""]
    (vd["dir"] / "overlay.md").write_text("\n".join(lines))


# ---------------------------------------------------------------- scenarios
def scenario_facts(u, tier_id, vd):
    o = overrides.get((u["unit_id"], tier_id))
    naics6 = o["naics6"] if o else u["primary_naics"]
    business = o["business"] if o else u["business"]
    system = o["primary_system"] if o else u["primary_system"]
    p = size_profile(tier_id, naics6)
    t = tiers[tier_id]
    companions = [c for c in u["multi_sector_companions"].split(";") if c]
    title = f"{COMPANY} | {u['name']} | {t['name']}"
    if tier_id == "t6":
        business = f"{business} (one division of a diversified holding company)"
    return {
        "company": COMPANY, "scenario_title": title, "tier_name": t["name"], "vertical_name": u["name"],
        "naics": naics6, "business": business, "headcount": headcount_text(p), "system_name": system,
        "ir_scenario": u["ir_scenario"], "ai_use_case": u["ai_use_case"],
        "primary_regulation": vd["profile"].get("primary_regulation", "[see vertical overlay]"),
        "date": TODAY, "_override": o, "_size": p, "_tier": t, "_companions": companions,
    }


def fill(text, f):
    return re.sub(r"\{\{(\w+)\}\}", lambda m: str(f.get(m.group(1), m.group(0))), text)


def rel(from_dir, to_path):
    return pathlib.Path(*[".."] * len(from_dir.relative_to(ROOT).parts)) / to_path.relative_to(ROOT)


def notification_rows(f, vd):
    """Vertical notifications plus cross-sector ones that apply to this tier."""
    out = []
    for n in vd["notifications"]:
        out.append([n["obligation"], n["citation"], n.get("trigger", ""), n["deadline"], n["notify"],
                    "Verify applicability", n["source_url"], n["verified"]])
    tier_id = [k for k, v in tiers.items() if v["name"] == f["tier_name"]][0]
    vertical_text = " ".join(n["citation"] + " " + n["obligation"] for n in vd["notifications"])
    for n in cross_notify:
        own = n["citation"] + " " + n["obligation"]
        if any(re.search(k, own) and re.search(k, vertical_text) for k in DEDUP_KEYS):
            continue
        if tier_id in n["tiers"].split(";"):
            out.append([n["obligation"], n["citation"], n["trigger"], n["deadline"], n["notify"],
                        n["applies_when"], n["source_url"], n["verified"]])
    return out


def write_scenario(u, tier_id, vd):
    f = scenario_facts(u, tier_id, vd)
    t, p, o = f["_tier"], f["_size"], f["_override"]
    d = unit_dir(u, S) / t["slug"]
    d.mkdir(parents=True, exist_ok=True)
    legal = {"t1": COMPANY, "t2": f"{COMPANY}, LLC", "t3": f"{COMPANY}, LLC",
             "t4": f"{COMPANY}, Inc.", "t5": f"{COMPANY}, Inc.", "t6": f"{COMPANY} Holdings, Inc."}[tier_id]

    # ---- meeting brief
    role = as_role(o["business"] if o else u["business"])
    intro = {
        "t1": f"{COMPANY} is a one-person business: Cris Santos owns and runs it alone as a sole proprietorship, operating as {role}.",
        "t2": f"{legal} is a micro business with {p['employees']} employees, operating as {role}.",
        "t3": f"{legal} is a small business with {p['employees']:,} employees, operating as {role}.",
        "t4": f"{legal} is a privately held mid-market company with {p['employees']:,} employees, operating as {role}.",
        "t5": f"{legal} is a publicly traded enterprise with {p['employees']:,} employees, operating as {role}.",
        "t6": (f"{legal} is a publicly traded, diversified enterprise with {p['employees']:,} employees. Its "
               f"{u['name']} division, the focus of this scenario, operates as {role}. The company also runs divisions in "
               + " and ".join(f"NAICS {c} {sector_names.get(c, '')}" for c in f["_companions"]) + "."),
    }[tier_id]
    size_rows = [("Employees", headcount_text(p))]
    if p["receipts"] is not None:
        size_rows.append(("Annual receipts (fictional)", money(p["receipts"])))
    if p["assets"] is not None:
        size_rows.append(("Total assets (fictional)", money(p["assets"])))
    pr = vd["profile"]
    L = [GENERATED, f"# {f['scenario_title']}", "", f"> {intro}", "",
         "This folder is a complete, self-contained sample. Read this page first, then open any project folder (P01-P10). "
         "Each project folder has a `_context.md` explaining what that deliverable looks like for this company.", "",
         "## At a glance", "| | |", "|---|---|",
         f"| Legal name | {legal} |", f"| Legal form | {t['legal_form']} |", f"| Ownership | {t['ownership']} |"]
    L += [f"| {k} | {v} |" for k, v in size_rows]
    L += [f"| Size tier | {t['name']}: {t['definition']} |",
          f"| SBA size status | {p['sba_status']} |",
          f"| Primary industry | NAICS {f['naics']} {p['industry_title']} |",
          f"| Vertical | {u['name']} ({'NAICS sector ' + u['naics_sector'] if u['level'] == 'naics_sector' else 'CISA critical infrastructure sector'}) |",
          f"| Primary system | {f['system_name']} |",
          f"| IT footprint | {t['it_footprint']} |",
          f"| Who owns security and compliance | {t['grc_owner']} |", ""]
    if p["flag"]:
        L += [f"> **Sizing note:** {p['flag']}", ""]
    if o:
        L += [f"> **Industry note:** At this size, {COMPANY} works in the {u['name']} vertical as "
              f"{as_role(o['business'])} (NAICS {o['naics6']}) instead of the vertical's primary industry "
              f"(NAICS {u['primary_naics']}). Reason: {o['rationale']}. Some sector rules may reach it only through "
              "customer contracts (flow-down). Confirming that is part of P03.", ""]
    L += ["## What the business handles",
          f"- **Sensitive data:** {pr.get('sensitive_data', '[see vertical overlay]')}",
          f"- **Critical systems:** {pr.get('critical_systems', '[see vertical overlay]')}", "",
          "## Who regulates it",
          pr.get("regulators", "[see vertical overlay]"), "",
          "| Requirement | Citation | Size thresholds / exemptions |", "|---|---|---|"]
    for r in vd["requirements"]:
        L.append(f"| [{md_escape(r['short_name'])}]({r['source_url']}) | {md_escape(r['citation'])} | {md_escape(r['size_thresholds'])} |")
    L += ["", "Whether each requirement applies at this size is decided in P03 (gap analysis), step 1.", "",
          "## The 10 projects for this company", "| # | Project | What it covers here |", "|---|---|---|"]
    for pj in projects:
        sc = scaling[(tier_id, pj["project_id"])]
        extra = {"P02": f" System: {f['system_name']}.", "P03": f" Regulation: {f['primary_regulation']}.",
                 "P08": f" Incident: {f['ir_scenario']}.", "P10": f" AI use case: {f['ai_use_case']}."}.get(pj["project_id"], "")
        L.append(f"| {pj['project_id']} | [{pj['name']}]({pj['slug']}/_context.md) | {sc['scope']}. {sc['expected_depth']}.{extra} |")
    L += ["", "## How to use this page in a meeting",
          "1. Read **At a glance** aloud. It sets who the company is and how big it is.",
          "2. Walk through **Who regulates it**. It explains why the projects exist.",
          "3. Open one project folder and its `_context.md`, then the working files next to it.", "",
          "## Where this comes from",
          f"- Universal methods: [`00_universal/`]({rel(d, U / 'README.md')})",
          f"- Tier definition: [`01_tiers/tiers.csv`]({rel(d, T / 'tiers.csv')})",
          f"- Vertical overlay: [`overlay.md`]({rel(d, vd['dir'] / 'overlay.md')})",
          f"- Generated {TODAY}. Size facts are fictional but consistent with the cited SBA and Census definitions.", ""]
    (d / "README.md").write_text("\n".join(L))

    # ---- project folders
    for pj in projects:
        pd = d / pj["slug"]
        pd.mkdir(exist_ok=True)
        src = U / "projects" / pj["slug"]
        sc = scaling[(tier_id, pj["project_id"])]
        C = [GENERATED, f"# {pj['project_id']} {pj['name']}: {f['scenario_title']}", "",
             "| | |", "|---|---|",
             f"| Scope at this tier | {sc['scope']} |", f"| Expected depth | {sc['expected_depth']} |",
             f"| Deliverable form | {sc['artifact_form']} |",
             f"| Universal method | [{pj['slug']}/README.md]({rel(pd, src / 'README.md')}) |",
             f"| Scenario brief | [README.md](../README.md) |", ""]
        if pj["project_id"] == "P02":
            C += [f"**System to document:** {f['system_name']}", ""]
        if pj["project_id"] == "P03":
            C += [f"**Regulation to analyze:** {f['primary_regulation']}, {pr.get('primary_regulation_citation', '')}",
                  f"**Why:** {pr.get('primary_regulation_rationale', '')}", ""]
            if o:
                C += [f"**Applicability check first:** at this size the business is {as_role(o['business'])}. "
                      f"Decide whether {f['primary_regulation']} applies directly or only through contracts. If it does "
                      "not apply, analyze the regulation that governs this business, and record the reasoning.", ""]
        if pj["project_id"] == "P08":
            C += [f"**Incident type:** {f['ir_scenario']}", "",
                  "**Pre-filled notification obligations** (also written to `notification-matrix.csv` when first created):", "",
                  "| Obligation | Citation | Deadline | Notify | Applies when |", "|---|---|---|---|---|"]
            C += [f"| {md_escape(n[0])} | {md_escape(n[1])} | {md_escape(n[3])} | {md_escape(n[4])} | {md_escape(n[5])} |"
                  for n in notification_rows(f, vd)]
            C += [""]
        if pj["project_id"] == "P09":
            C += [f"**Assurance alternatives in this vertical:** {pr.get('assurance_alternatives', '') or 'None noted'}", ""]
        if pj["project_id"] == "P10":
            C += [f"**AI use case:** {f['ai_use_case']}",
                  f"**Sector AI rules and guidance:** {pr.get('ai_specific', '') or 'None identified; see cross-sector obligations'}",
                  f"**Cross-sector AI obligations:** [`00_universal/cross-sector/`]({rel(pd, U / 'cross-sector')})", ""]
        C += ["## Regulatory drivers to trace in this deliverable",
              "Use these IDs in the `regulatory_driver` columns of the working files.", "",
              "| ID | Requirement | Citation |", "|---|---|---|"]
        C += [f"| {r['req_id']} | {md_escape(r['short_name'])} | {md_escape(r['citation'])} |" for r in vd["requirements"]]
        C += ["", "## Working files in this folder",
              "These files were copied from the universal templates with scenario details filled in. Replace every `[FILL]` marker. "
              "The build never overwrites them after they exist.", ""]
        for tf in pj["template_files"].split(";"):
            C.append(f"- [`{tf}`]({tf})")
            target = pd / tf
            if FORCE or not target.exists():
                if pj["project_id"] == "P08" and tf == "notification-matrix.csv":
                    with open(target, "w", newline="") as fh:
                        w = csv.writer(fh, lineterminator="\n")
                        w.writerow(["obligation", "citation", "trigger", "deadline", "notify", "applies_at_this_tier", "source_url", "verified"])
                        w.writerows(notification_rows(f, vd))
                else:
                    target.write_text(fill((src / tf).read_text(), f))
        (pd / "_context.md").write_text("\n".join(C) + "\n")
    return d, f


def main():
    if not (V / "sba-size-standards.csv").exists():
        sys.exit("Run tools/refresh_sba_standards.py first.")
    index = [GENERATED, f"# Scenario index: {COMPANY}", "",
             f"{len(units)} verticals x {len(tiers)} tiers = {len(units) * len(tiers)} scenarios. "
             "NAICS sectors are bold; CISA sectors are nested beneath their parent sector.", "",
             "| Vertical | " + " | ".join(t["name"] for t in tiers.values()) + " |",
             "|---|" + "---|" * len(tiers)]
    ordered = []
    for u in units:
        if u["level"] == "naics_sector":
            ordered.append(u)
            ordered += [k for k in units if k["parent_id"] == u["unit_id"]]
    count = 0
    for u in ordered:
        vd = vertical_data(u)
        vd["dir"].mkdir(parents=True, exist_ok=True)
        write_overlay(u, vd)
        cells = []
        for tid in tiers:
            d, _ = write_scenario(u, tid, vd)
            count += 1
            cells.append(f"[open]({d.relative_to(S)}/README.md)")
        label = f"**{u['naics_sector']} {u['name']}**" if u["level"] == "naics_sector" else f"&nbsp;&nbsp;↳ {u['name']} (CISA)"
        index.append(f"| {label} | " + " | ".join(cells) + " |")
    (S / "INDEX.md").write_text("\n".join(index) + "\n")
    print(f"Built {count} scenarios across {len(ordered)} verticals.")


if __name__ == "__main__":
    main()
